FROM node:18.7.0-alpine3.15 as build

WORKDIR /app

RUN addgroup app && \
    adduser -S -G app app
    
COPY ["package.json", "yarn.lock", "./"]

RUN yarn 

COPY . .

RUN yarn build

# 2nd stage
FROM bitnami/nginx:1.25.3

COPY --from=build /app/dist /opt/bitnami/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]