FROM node:18.7.0-alpine3.15 as build

WORKDIR /app

RUN addgroup app && \
    adduser -S -G app app
    
COPY ["package.json", "yarn.lock", "./"]

RUN yarn 

COPY . .

RUN yarn build

# 2nd stage
FROM nginx:1.23.3-alpine-slim

COPY --from=build /app/dist /etc/nginx/html
   
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]